# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GMDToolkits
                                 A QGIS plugin
 test
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-01-29
        copyright            : (C) 2025 by Kent Emman
        email                : email@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Kent Emman'
__date__ = '2025-01-29'
__copyright__ = '(C) 2025 by Kent Emman'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GMDToolkits class from file GMDToolkits.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gmd_toolkits import GMDToolkitsPlugin
    return GMDToolkitsPlugin()
